# Generated by Django 4.2.10 on 2024-03-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='date_time',
        ),
    ]
