# Generated by Django 4.2.10 on 2024-03-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_remove_training_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='author',
            field=models.CharField(default='User_id', max_length=20),
        ),
    ]
