# Generated by Django 4.2.10 on 2024-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_training_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='logo',
            field=models.ImageField(default=2, upload_to='logotypes'),
            preserve_default=False,
        ),
    ]
