# Generated by Django 4.2.10 on 2024-03-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_training_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='logo',
            field=models.ImageField(upload_to='logotypes/'),
        ),
    ]
