# Generated by Django 4.2.10 on 2024-03-11 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
